gcc_version:
  - 15.2.0
  - 14.3.0
  - 13.4.0
libgfortran_soname:
  - 5
binutils_version:
  - 2.44
cross_target_platform:
  - linux-64
  - linux-ppc64le
  - linux-aarch64
  - linux-s390x
  - win-64
  - osx-64
  - osx-arm64
triplet:
  - x86_64-conda-linux-gnu
  - powerpc64le-conda-linux-gnu
  - aarch64-conda-linux-gnu
  - s390x-conda-linux-gnu
  - x86_64-w64-mingw32
  - x86_64-apple-darwin13.4.0
  - arm64-apple-darwin20.0.0
c_stdlib:          # [win]
  - m2w64-sysroot  # [win]
c_stdlib_version:  # [win]
  - 12             # [win]
cross_stdlib:
  - sysroot
  - sysroot
  - sysroot
  - sysroot
  - m2w64-sysroot
  - None
  - None
cross_stdlib_version:
  - 2.17
  - 2.17
  - 2.17
  - 2.17
  - 12
  - None
  - None
clang_version:
  - 21.1
  - 20.1
  - 19.1

zip_keys:
  - - cross_target_platform
    - triplet
    - cross_stdlib
    - cross_stdlib_version
