# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      linux_64_cross_stdlibm2w64-sysrootcross_stdlib_version12cross_target_platformwin-64gcc_version12.3.0:
        CONFIG: linux_64_cross_stdlibm2w64-sysrootcross_stdlib_version12cross_target_platformwin-64gcc_version12.3.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_cross_stdlibm2w64-sysrootcross_stdlib_version12cross_target_platformwin-64gcc_version13.2.0:
        CONFIG: linux_64_cross_stdlibm2w64-sysrootcross_stdlib_version12cross_target_platformwin-64gcc_version13.2.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_cross_stdlibsysrootcross_stdlib_version2.12cross_target_platformlinux-64gcc_version12.3.0:
        CONFIG: linux_64_cross_stdlibsysrootcross_stdlib_version2.12cross_target_platformlinux-64gcc_version12.3.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_cross_stdlibsysrootcross_stdlib_version2.12cross_target_platformlinux-64gcc_version13.2.0:
        CONFIG: linux_64_cross_stdlibsysrootcross_stdlib_version2.12cross_target_platformlinux-64gcc_version13.2.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-aarch64gcc_version12.3.0:
        CONFIG: linux_64_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-aarch64gcc_version12.3.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-aarch64gcc_version13.2.0:
        CONFIG: linux_64_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-aarch64gcc_version13.2.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-ppc64legcc_version12.3.0:
        CONFIG: linux_64_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-ppc64legcc_version12.3.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-ppc64legcc_version13.2.0:
        CONFIG: linux_64_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-ppc64legcc_version13.2.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-s390xgcc_version12.3.0:
        CONFIG: linux_64_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-s390xgcc_version12.3.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-s390xgcc_version13.2.0:
        CONFIG: linux_64_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-s390xgcc_version13.2.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_aarch64_cross_stdlibm2w64-sysrootcross_stdlib_version12cross_target_platformwin-64gcc_version12.3.0:
        CONFIG: linux_aarch64_cross_stdlibm2w64-sysrootcross_stdlib_version12cross_target_platformwin-64gcc_version12.3.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_aarch64_cross_stdlibm2w64-sysrootcross_stdlib_version12cross_target_platformwin-64gcc_version13.2.0:
        CONFIG: linux_aarch64_cross_stdlibm2w64-sysrootcross_stdlib_version12cross_target_platformwin-64gcc_version13.2.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_aarch64_cross_stdlibsysrootcross_stdlib_version2.12cross_target_platformlinux-64gcc_version12.3.0:
        CONFIG: linux_aarch64_cross_stdlibsysrootcross_stdlib_version2.12cross_target_platformlinux-64gcc_version12.3.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_aarch64_cross_stdlibsysrootcross_stdlib_version2.12cross_target_platformlinux-64gcc_version13.2.0:
        CONFIG: linux_aarch64_cross_stdlibsysrootcross_stdlib_version2.12cross_target_platformlinux-64gcc_version13.2.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_aarch64_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-aarch64gcc_version12.3.0:
        CONFIG: linux_aarch64_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-aarch64gcc_version12.3.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_aarch64_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-aarch64gcc_version13.2.0:
        CONFIG: linux_aarch64_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-aarch64gcc_version13.2.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_aarch64_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-ppc64legcc_version12.3.0:
        CONFIG: linux_aarch64_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-ppc64legcc_version12.3.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_aarch64_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-ppc64legcc_version13.2.0:
        CONFIG: linux_aarch64_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-ppc64legcc_version13.2.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_aarch64_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-s390xgcc_version12.3.0:
        CONFIG: linux_aarch64_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-s390xgcc_version12.3.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_aarch64_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-s390xgcc_version13.2.0:
        CONFIG: linux_aarch64_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-s390xgcc_version13.2.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_ppc64le_cross_stdlibm2w64-sysrootcross_stdlib_version12cross_target_platformwin-64gcc_version12.3.0:
        CONFIG: linux_ppc64le_cross_stdlibm2w64-sysrootcross_stdlib_version12cross_target_platformwin-64gcc_version12.3.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_ppc64le_cross_stdlibm2w64-sysrootcross_stdlib_version12cross_target_platformwin-64gcc_version13.2.0:
        CONFIG: linux_ppc64le_cross_stdlibm2w64-sysrootcross_stdlib_version12cross_target_platformwin-64gcc_version13.2.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_ppc64le_cross_stdlibsysrootcross_stdlib_version2.12cross_target_platformlinux-64gcc_version12.3.0:
        CONFIG: linux_ppc64le_cross_stdlibsysrootcross_stdlib_version2.12cross_target_platformlinux-64gcc_version12.3.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_ppc64le_cross_stdlibsysrootcross_stdlib_version2.12cross_target_platformlinux-64gcc_version13.2.0:
        CONFIG: linux_ppc64le_cross_stdlibsysrootcross_stdlib_version2.12cross_target_platformlinux-64gcc_version13.2.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_ppc64le_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-aarch64gcc_version12.3.0:
        CONFIG: linux_ppc64le_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-aarch64gcc_version12.3.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_ppc64le_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-aarch64gcc_version13.2.0:
        CONFIG: linux_ppc64le_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-aarch64gcc_version13.2.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_ppc64le_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-ppc64legcc_version12.3.0:
        CONFIG: linux_ppc64le_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-ppc64legcc_version12.3.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_ppc64le_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-ppc64legcc_version13.2.0:
        CONFIG: linux_ppc64le_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-ppc64legcc_version13.2.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_ppc64le_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-s390xgcc_version12.3.0:
        CONFIG: linux_ppc64le_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-s390xgcc_version12.3.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_ppc64le_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-s390xgcc_version13.2.0:
        CONFIG: linux_ppc64le_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-s390xgcc_version13.2.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_s390x_cross_stdlibm2w64-sysrootcross_stdlib_version12cross_target_platformwin-64gcc_version12.3.0:
        CONFIG: linux_s390x_cross_stdlibm2w64-sysrootcross_stdlib_version12cross_target_platformwin-64gcc_version12.3.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_s390x_cross_stdlibm2w64-sysrootcross_stdlib_version12cross_target_platformwin-64gcc_version13.2.0:
        CONFIG: linux_s390x_cross_stdlibm2w64-sysrootcross_stdlib_version12cross_target_platformwin-64gcc_version13.2.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_s390x_cross_stdlibsysrootcross_stdlib_version2.12cross_target_platformlinux-64gcc_version12.3.0:
        CONFIG: linux_s390x_cross_stdlibsysrootcross_stdlib_version2.12cross_target_platformlinux-64gcc_version12.3.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_s390x_cross_stdlibsysrootcross_stdlib_version2.12cross_target_platformlinux-64gcc_version13.2.0:
        CONFIG: linux_s390x_cross_stdlibsysrootcross_stdlib_version2.12cross_target_platformlinux-64gcc_version13.2.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_s390x_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-aarch64gcc_version12.3.0:
        CONFIG: linux_s390x_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-aarch64gcc_version12.3.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_s390x_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-aarch64gcc_version13.2.0:
        CONFIG: linux_s390x_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-aarch64gcc_version13.2.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_s390x_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-ppc64legcc_version12.3.0:
        CONFIG: linux_s390x_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-ppc64legcc_version12.3.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_s390x_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-ppc64legcc_version13.2.0:
        CONFIG: linux_s390x_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-ppc64legcc_version13.2.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_s390x_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-s390xgcc_version12.3.0:
        CONFIG: linux_s390x_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-s390xgcc_version12.3.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_s390x_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-s390xgcc_version13.2.0:
        CONFIG: linux_s390x_cross_stdlibsysrootcross_stdlib_version2.17cross_target_platformlinux-s390xgcc_version13.2.0
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
  timeoutInMinutes: 360
  variables: {}

  steps:
  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: |
        export CI=azure
        export flow_run_id=azure_$(Build.BuildNumber).$(System.JobAttempt)
        export remote_url=$(Build.Repository.Uri)
        export sha=$(Build.SourceVersion)
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        if [[ "${BUILD_REASON:-}" == "PullRequest" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)